# General Configuration
postgresVersion: 15

# Basic Postgres Settings
instanceName: instance1
instanceSize: 50Gi
instanceStorageClassName: "oci-bv"
instanceMemory: 2Gi
instanceCPU: 1000m
instanceReplicas: 1  # This is for the primary instance

# Advanced Postgres Settings for multiple replicas
instances:
  - name: replica1
    replicas: 1  # Number of replicas you want
    dataVolumeClaimSpec:
      accessModes:
      - "ReadWriteOnce"
      storageClassName: oci-bv
      resources:
        requests:
          storage: 50Gi

# Monitoring - enabling it
monitoring: true

# The rest of the settings can be defaults or customized based on further needs
